server:
  port: 5737

spring:
  application:
    name: population-service
  datasource:
    url: jdbc:postgresql://localhost:5417/db
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # или validate, если база уже создана
    show-sql: true
    properties:
      hibernate:
        format_sql: true

city:
  service:
    url: https://127.0.0.1:5736/api/v1
    username: user
    password: password

# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
